name: Run Python Script Pipeline

# Triggers the workflow on push or pull request events for the main branch, or manually
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: # Allows you to manually trigger the pipeline from the GitHub UI

jobs:
  execute-script:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository code onto the runner
    - name: Checkout repository code
      uses: actions/checkout@v4

    # Step 2: Set up the Python environment
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-python-version: '3.11' # Specify your preferred Python version

    # Step 3: Install dependencies if a requirements file exists
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # Step 4: Run your Python script
    - name: Execute Python script
      run: python script.py
  
    - name: Polaris Scan
      uses: blackduck-inc/black-duck-security-scan@v2
      with:
        ### SCANNING: Required fields
        polaris_server_url: https://poc.polaris.blackduck.com
        polaris_access_token: jrgodvf36h0gncgq430cc0htnl86o8vpdc44ghdjulhbvfm4ctknff00hudrg18fgok7cpd0qldnk
        polaris_assessment_types: "SCA,SAST"
        
        ### SCANNING OPTIONAL
        polaris_application_name: quickstart-${{ github.event.repository.name }}
        
        ### SCANNING OPTIONAL: Pull Request comments
        polaris_prComment_enabled: true
        
        ### SCANNING OPTIONAL: GitHub Issues
        polaris_externalIssues_create: true

        ### SCANNING OPTIONAL: Fix Pull Requests
        polaris_fixpr_enabled: true

        ### GITHUB Token
        # Required when Pull Request comments, Fix Pull Requests or GitHub issues are enabled
        github_token: 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

        ### ENABLE OPTIONAL SCAN REPORTS
        polaris_reports_sarif_create: true
        polaris_upload_sarif_report: true
        
        ### COVERITY BUILD COMMANDS (uncomment and configure for compiled languages)
        # coverity_build_command: mvn -B -DskipTests package
        # coverity_clean_command: mvn -B clean
        
        ### OPTIONAL DIAGNOSTICS: Upload logs as build artifact if true
        include_diagnostics: false
